// Variables
let firstName = 'James';
const PI = 3.14;

// DATA TYPES
// Primitive data types in JavaScript include:
    // Numbers - Integers, floats
    // Strings - Any data under single quote, double quote or backtick quote
    // Booleans - true or false value
    // Null - empty value or no value
    // Undefined - a declared variable without a value
    // Symbol - A unique value that can be generated by Symbol constructor
    
// Non-primitive data types in JavaScript includes:
    // Objects
    // Arrays

// - Primitive data types
    // Primitive data types are immutable(non-modifiable) data types 
        // Strings:
        let word = 'JavaScript';
        // Attempting to modify the string should return error
        // This expression would NOT change the 'word' variable
        word[0] = 'Y';
        console.log(word); // Should return 'JavaScript'

    // Primitive data types are compared by its values
        // Strings:
            let js = 'JavaScript';
            let py = 'Python';
            console.log(js == py); // false
        
        // Integers:
            let numOne = 3;
            let numTwo = 3;
            console.log(numOne == numTwo); // true

        // Booleans:
            let ligtOn = true;
            let ligtOff = false;
            console.log(ligtOn == ligtOff); // false

// - Non-primitive data types(Object References)
    // Non-primitive data types are modifiable or mutable
        // Arrays:
            let nums = [1, 2, 3];
            nums[0] = 10;
            console.log(nums) // [10, 2, 3];
            
    // Non-primitive data types cannot be compared by value
    // Even if two non-primitive data types have the same properties and values, they are not strictly equal
        // Objects:
            let useOne = {
                name:'James',
                role:'teaching',
                country:'United States'
            };

            let userTwo = {
                name:'James',
                role:'teaching',
                country:'United States'
            };
            console.log(useOne == userTwo); // false

    // Non-primitive values are referred to as reference types, 
    // because they are being compared by reference instead of value
    // Two objects are only strictly equal if they refer to the same underlying object
        // Objects:
            let nums2 = [1, 2, 3];
            let numbers = nums2;
            console.log(nums2 == numbers); // true
    
            let userThree = {
                name:'James',
                role:'teaching',
                country:'United States'
            };
            let userFour = userThree;
            console.log(userThree == userFour); // true


// NUMBERS
// Numbers are integers and decimal values which can do all the arithmetic operations
// Declaring Number Data Types:
let age = 35;
const gravity = 9.81 ; // we use const for non-changing values, gravitational constant in  m/s2
let mass = 72; // mass in Kilogram
const PI = 3.14; // pi a geometrical constant

// More Examples
const boilingPoint = 100; // temperature in oC, boiling point of water which is a constant
const bodyTemp = 37; // oC average human body temperature, which is a constant

console.log(age, gravity, mass, PI, boilingPoint, bodyTemp);


// Math Object:
// In JavaScript the Math Object provides a lots of methods to work with numbers
const PI = Math.PI

console.log(PI) // 3.141592653589793

// Rounding to the closest number
// if above .5 up if less 0.5 down rounding

console.log(Math.round(PI)) // 3 to round values to the nearest number

console.log(Math.round(9.81)) // 10

console.log(Math.floor(PI)) // 3 rounding down

console.log(Math.ceil(PI)) // 4 rounding up

console.log(Math.min(-5, 3, 20, 4, 5, 10)) // -5, returns the minimum value

console.log(Math.max(-5, 3, 20, 4, 5, 10)) // 20, returns the maximum value

const randNum = Math.random() // creates random number between 0 to 0.999999
console.log(randNum)

// Let us  create random number between 0 to 10

const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
console.log(num)

//Absolute value
console.log(Math.abs(-10))      // 10

//Square root
console.log(Math.sqrt(100))     // 10

console.log(Math.sqrt(2))       // 1.4142135623730951

// Power
console.log(Math.pow(3, 2))     // 9

console.log(Math.E)             // 2.718

// Logarithm
// Returns the natural logarithm with base E of x, Math.log(x)
console.log(Math.log(2))        // 0.6931471805599453
console.log(Math.log(10))       // 2.302585092994046

// Returns the natural logarithm of 2 and 10 respectively
console.log(Math.LN2)           // 0.6931471805599453
console.log(Math.LN10)          // 2.302585092994046

// Trigonometry
Math.sin(0)
Math.sin(60)

Math.cos(0)
Math.cos(60)


// Random Number Generator:
// The JavaScript Math Object has a random() method number generator which generates number from 0 to 0.999999999
let randomNum = Math.random() // generates 0 to 0.999

// Generate a random number between 0 and 10
let randomNum = Math.random()         // generates 0 to 0.999
let numBtnZeroAndTen = randomNum * 11

console.log(numBtnZeroAndTen)         // this gives: min 0 and max 10.99

let randomNumRoundToFloor = Math.floor(numBtnZeroAndTen)
console.log(randomNumRoundToFloor)    // this gives between 0 and 10



// ARRAYS
// Creating arrays:
// Using Array constructor
const arr1 = Array();
console.log(arr1);

let arr2 = Array();
console.log(arr2);

// Using square brackets:
const arr3 = [];
console.log(arr3);

// Array with values
const numbers = [0, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]; // number array
const armor = ['Knife', 'Nunchucks', 'Brass Knuckles','Shotgun', 'AK-47', 'Glock 9', 'Beretta', 'Uzi', 'MAC-10']; // armor array
const characters = ['James Bond', 'Max Payne', 'Stone Cold', 'The Rock', 'Ash', 'Goku', 'Vegetta', 'Ryu', 'Bison']; // characters array
const attacks = ['Punch', 'Kick', 'Push', 'Slice', 'Stab', 'Shoot']
const moves = [ {directions: ['Up', 'Down', 'Left', 'Right']} , 'Jump', 'Crouch', 'Reload', 'Change Weapon'];
const players = [ 1, 2, 3, 4, 5, 6];

// Print array and it's length
console.log('Numbers:', numbers);
console.log('Number of Numbers', numbers.length);

console.log('Armor:', armor);
console.log('Number Guns in Armor', armor.length);

console.log('Characters:', characters);
console.log('Number of Characters', characters.length);

console.log('Attacks:', attacks);
console.log('Number of Attacks', attacks.length);

console.log('Moves:', moves);
console.log('Number of Moves', moves.length);

console.log('Players:', players);
console.log('Number of Players', players.length);

